export default Object.freeze({
    PREDICT_CITIES: 'PREDICT_CITIES',
    SET_ACTIVE_CITY: 'SET_ACTIVE_CITY',
    SELECT_CITY: 'SELECT_CITY',
    CHANGE_INPUT: 'CHANGE_INPUT',
    RESET: 'RESET',
    ADD_CITY: 'ADD_CITY',
    REMOVE_CITY: 'REMOVE_CITY'
});
